TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += rkndio.db
DATA += rkndio.proto

#=======================================
include $(TOP)/configure/RULES
