TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += rkndio.db
DB += rkndio_pin_inputs.db
DB += rkndio_pin_outputs.db
DATA += rkndio.proto

#=======================================
include $(TOP)/configure/RULES
